### ISSUE TITLE
local dev: listen on more interfaces than localhost?

### ISSUE THREAD

**Issue by trombonekenny** [illinois/queue-info#9]
n00b question about the framework used here. I use a Linux system as my dev environment, but treat it mostly head-less. Browsers I'll run from whatever Windows or Mac system I'm actually sitting at.

What's the trick to getting next to listen on something other than localhost?

**Comment by nwalters512** [comment]
```
npm run dev -- --hostname localhost --port 4567
```

You can check out the docs for more details: https://github.com/zeit/next.js#starting-the-server-on-alternative-hostname
